views:
    - changed-files:
          - any-glob-to-any-file:
                - 'src/pages/**/*'
                - 'src/widgets/**/*'
                - 'src/app/layouts/**/*'

features:
    - changed-files:
          - any-glob-to-any-file:
                - 'src/features/**/*'

domain:
    - changed-files:
          - any-glob-to-any-file:
                - 'src/entities/**/*'

ui-kit:
    - changed-files:
          - any-glob-to-any-file:
                - 'src/shared/ui/**/*'
                - 'src/app/styles/**/*'
                - '.storybook/**/*'
                - '**/*.{css,scss}'

core-logic:
    - changed-files:
          - any-glob-to-any-file:
                - 'src/shared/{api,snippets,config,providers}/**/*'
                - 'src/app/providers/**/*'

docs:
    - changed-files:
          - any-glob-to-any-file:
                - 'package.json'
                - 'pnpm-lock.yaml'
                - 'pnpm-workspace.yaml'

devops:
    - changed-files:
          - any-glob-to-any-file:
                - 'infra/**/*'
                - '.github/workflows/**/*'
                - 'Dockerfile*'
                - '.dockerignore'

test:
    - changed-files:
          - any-glob-to-any-file:
                - 'test/**/*'
                - 'src/**/*.spec.{ts,js}'

config:
    - changed-files:
          - any-glob-to-any-file:
                - '*.config.*'
                - 'tsconfig.json'
                - '.env*'
                - '.eslintrc*'
                - '.prettier*'
          - all-globs-to-all-files:
                - '!package.json'

deps:
    - changed-files:
          - any-glob-to-any-file:
                - '**/*.md'
                - 'LICENSE'
