import { defineConfig } from 'oxlint';

export default defineConfig({
    categories: {
        correctness: 'error',
        perf: 'warn',
        nursery: 'warn',
        style: 'warn',
    },

    rules: {
        'no-ternary': 'off',
        'no-magic-numbers': 'off',
        'one-var': 'off',
        'func-style': 'allow',
        'new-cap': 'off',
        'no-console': 'warn',
        'no-debugger': 'error',
        'prefer-const': 'error',
        'no-var': 'error',
        eqeqeq: ['error', 'always'],
        curly: ['error', 'all'],
        'no-undef': 'error',
        'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
        'no-implicit-globals': 'error',
        'no-shadow': 'error',
        'no-param-reassign': 'warn',
        'prefer-template': 'warn',
        'prefer-arrow-callback': 'warn',
        'prefer-destructuring': 'warn',
        'no-array-constructor': 'error',
        'object-shorthand': ['error', 'always'],
        'no-prototype-builtins': 'warn',
        'no-useless-constructor': 'warn',
        'no-useless-escape': 'warn',
        'no-useless-catch': 'warn',
        'no-useless-return': 'warn',
        'no-unnecessary-type-assertion': 'warn',
        'no-unsafe-optional-chaining': 'error',
        'no-unsafe-negation': 'error',
        'no-unsafe-finally': 'error',
        'no-promise-executor-return': 'error',
        'no-await-in-loop': 'warn',

        'ban-types': 'warn',
        'no-explicit-any': 'warn',
        'no-inferrable-types': 'warn',
        'no-non-null-assertion': 'warn',
        'no-require-imports': 'error',
        'no-var-requires': 'error',
        'prefer-as-const': 'error',
        'prefer-for-of': 'warn',
        'prefer-function-type': 'warn',
        'prefer-includes': 'warn',
        'prefer-nullish-coalescing': 'warn',
        'prefer-optional-chain': 'warn',
        'prefer-readonly': 'warn',
        'adjacent-overload-signatures': 'error',

        'jsx-no-useless-fragment': 'warn',
        'jsx-key': 'error',
        'jsx-no-duplicate-props': 'error',
        'jsx-no-script-url': 'error',
        'jsx-no-target-blank': 'warn',
        'jsx-no-comment-textnodes': 'warn',
        'jsx-no-constructed-context-values': 'warn',
        'react/jsx-props-no-spreading': 'off',

        '@next/next/no-html-link-for-pages': 'error',
        '@next/next/no-img-element': 'warn',
        '@next/next/no-unwanted-polyfillio': 'warn',
        '@next/next/google-font-display': 'warn',
        '@next/next/google-font-preconnect': 'warn',
        '@next/next/no-head-element': 'warn',
        '@next/next/no-head-import-in-document': 'warn',
        '@next/next/no-page-custom-font': 'warn',
        '@next/next/no-sync-scripts': 'warn',
        '@next/next/no-typos': 'error',
        '@next/next/no-title-in-document-head': 'warn',
        '@next/next/no-document-import-in-page': 'error',
        '@next/next/no-script-component-in-head': 'error',
        '@next/next/no-before-interactive-script-outside-document': 'warn',
        '@next/next/inline-script-id': 'error',
    },

    ignorePatterns: [
        '**/node_modules/**',
        '**/.pnpm-store/**',

        '**/dist/**',
        '**/build/**',
        '**/.next/**',
        '**/out/**',
        '**/coverage/**',

        '**/.turbo/**',
        '**/.cache/**',

        '**/*.test.ts',
        '**/*.test.tsx',
        '**/*.spec.ts',
        '**/*.spec.tsx',
        '**/__tests__/**',
        '**/__mocks__/**',

        '**/.storybook/**',
        '**/storybook-static/**',

        '**/*.generated.ts',
        '**/generated/**',

        '**/*.min.js',
        '**/*.bundle.js',

        '**/next-env.d.ts',

        '**/.env*',

        '**/*.log',
        '**/coverage/**',
        '**/.vercel/**',
        '**/.netlify/**',

        '**/*.config.ts',
        '**/*.config.js',
        '**/*.config.mjs',
        '**/*.config.cjs',
    ],

    plugins: ['react-perf', 'nextjs', 'react', 'typescript'],

    overrides: [
        {
            files: ['scripts/**'],
            env: { node: true },
            rules: {
                'no-console': 'off',
            },
        },
    ],
});
