import '../src/shared/styles/globals.css';
import type { Metadata } from 'next';
import { Inter, JetBrains_Mono } from 'next/font/google';
import { cn } from '~&/shared/lib/utils';

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-mono' });

const inter = Inter({
    adjustFontFallback: true,
    display: 'swap',
    subsets: ['latin'],
    variable: '--font-inter',
});

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
};

export default function RootLayout({ children }: React.PropsWithChildren) {
    return (
        <html
            lang="en"
            className={cn(
                'h-full',
                'antialiased',
                'font-mono',
                jetbrainsMono.variable,
                inter.variable,
            )}
        >
            <body className="flex min-h-full flex-col">{children}</body>
        </html>
    );
}
