import './globals.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

const geistSans = Geist({
        subsets: ['latin'],
        variable: '--font-geist-sans',
    }),
    geistMono = Geist_Mono({
        subsets: ['latin'],
        variable: '--font-geist-mono',
    });

export const metadata: Metadata = {
    description: 'Generated by create next app',
    title: 'Create Next App',
};

export default function RootLayout({ children }: React.PropsWithChildren) {
    return (
        <html
            lang="en"
            className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
            <body className="flex min-h-full flex-col">{children}</body>
        </html>
    );
}
