name: CI

on:
    push:
        branches:
            - master
            - dev
            - 'feat/**'
            - 'fix/**'
            - 'refactor/**'
            - 'chore/**'
            - 'perf/**'
            - 'build/**'
            - 'ci/**'
        paths-ignore:
            - '**.md'
            - 'infra/**'
            - '.gitignore'
            - 'docker-compose.yml'

    pull_request:
        branches:
            - master
            - dev
        paths-ignore:
            - '**.md'
            - 'infra/**'
    workflow_dispatch:

permissions:
    contents: read
    actions: write

jobs:
    quality-check:
        name: Lint & Test
        uses: deView-inc/.github/.github/workflows/ci-base.yml@master
        with:
            node-version: 24
            lint-command: pnpm run lint
            type-check-command: pnpm exec tsc --noEmit
